sudo: required
language: node_js
node_js:
  - "8.11"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

git:
  depth: 1

cache:
  npm: true
  directories:
     - ./node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  - TASK=release
  - TASK=test
  - TASK=test:schematics
  - TASK=lint
  - TASK=site:release
  - TASK=scaffold:release

matrix:
  fast_finish: true
  allow_failures:
    - env: "TASK=site:release"
    - env: "TASK=scaffold:release"

script:
  - npm run $TASK
  - |
    if [ "$TASK" = "test" ]; then
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
    fi
